# Generated by Django 5.0.1 on 2024-01-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_cases', models.IntegerField()),
                ('total_cases', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('per_1M', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('per_1M', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('population', models.IntegerField()),
                ('cases', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='countries.case')),
                ('deaths', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='countries.death')),
                ('tests', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='countries.test')),
            ],
        ),
    ]
