# Generated by Django 4.2 on 2024-01-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_infected', models.IntegerField()),
                ('total_infected', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('cases_per_1M', models.IntegerField()),
                ('total_tests', models.IntegerField()),
                ('test_per_1M', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notification', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='country',
            name='date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tests',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Death',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='countries.country'),
        ),
        migrations.AddField(
            model_name='data',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='countries.country'),
        ),
        migrations.AddField(
            model_name='countries_user',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AddField(
            model_name='countries_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.user'),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('country', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='countries_user',
            unique_together={('country', 'user')},
        ),
    ]
