# Generated by Django 4.2 on 2024-01-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_countries_user_data_user_remove_country_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.AddField(
            model_name='data',
            name='population',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
