# Generated by Django 4.2 on 2024-01-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_remove_country_population_data_population'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries_User',
        ),
    ]
